package foundation.mee.android_client.models

import uniffi.mee_agent.OidcClientMetadata
import kotlin.random.Random

fun getMockConnectors(): List<MeeConnector> {
    return phraseList.map {
        val id = "https://${it}"
        val name = it
        val otherPartyConnectionId = it

        val randomConnectorType = /*when (Random.nextBoolean()) {
                true -> */MeeConnectorType.Siop(
            SiopConnectorType(
                redirectUri = "https://${it}",
                clientMetadata = PartnerMetadata(
                    from = OidcClientMetadata(
                        applicationType = when (Random.nextBoolean()) {
                            true -> ClientType.mobile.name
                            false -> ClientType.web.name
                        },
                        clientName = it,
                        logoUri = "https://${it}/favicon.png",
                        contacts = emptyList(),
                        jwks = null,
                        jwksUri = null,
                        idTokenSignedResponseAlg = null,
                        idTokenEncryptedResponseAlg = null,
                        idTokenEncryptedResponseEnc = null,
                        subjectSyntaxTypesSupported = listOf()
                    )
                ),
                subjectSyntaxType = ConnectorTypeSubject.DidKey("")
            )
        )

        /*  false -> MeeConnectorType.Gapi(GapiConnectorType(scopes = listOf()))
      }
*/
        MeeConnector(id, name, otherPartyConnectionId, randomConnectorType)
    }
}

val phraseList = listOf(
    "sit rain",
    "horse boat",
    "language was",
    "stop phrase",
    "root half",
    "it his",
    "stay can",
    "how climb",
    "baby hill",
    "you mean",
    "minute beauty",
    "body pass",
    "fight cook",
    "island had",
    "ground draw",
    "held three",
    "area made",
    "shape name",
    "seem strange",
    "people several",
    "I children",
    "air word",
    "unit instrument",
    "until energy",
    "silent again",
    "river wait",
    "object ball",
    "found music",
    "interest feet",
    "single certain",
    "feel near",
    "east describe",
    "include paint",
    "about every",
    "country would",
    "now board",
    "consider together",
    "heavy follow",
    "mind happen",
    "their boy",
    "speed century",
    "design say",
    "stead head",
    "organ center",
    "lone ease",
    "have snow",
    "finish cross",
    "those king",
    "burn find",
    "new time",
    "come page",
    "metal then",
    "window all",
    "subject lie",
    "play animal",
    "me got",
    "must distant",
    "fish what",
    "wonder spring",
    "toward product",
    "went grand",
    "fun walk",
    "fun calk",
    "fun balk",
    "fue walk",
    "fuu walk",
    "town friend",
    "group tree",
    "long rest",
    "paper perhaps",
    "forest four",
    "meet second",
    "thing make",
    "could line",
    "know too",
    "before table",
    "enough else",
    "young joy",
    "direct measure",
    "order jump",
    "her view",
    "rule middle",
    "wheel want",
    "large moment",
    "quite fly",
    "kept bear",
    "hold ear",
    "finger seven",
    "like state",
    "place blue",
    "girl law",
    "among your",
    "contain box",
    "that test",
    "if written",
    "square care",
    "sun heart",
    "figure voice",
    "plane numeral",
    "ago and",
    "cell course",
    "quick person",
    "loud leg",
    "pull map",
    "lake busy",
    "stick wind",
    "fact money",
    "happy record",
    "star might",
    "mark first",
    "yet during",
    "push behind",
    "an always",
    "special turn",
    "show able",
    "we close",
    "note war",
    "am space",
    "cover will",
    "my govern",
    "true black",
    "mother drive",
    "straight plant",
    "tire dictionary",
    "reason early",
    "sense remember",
    "catch light",
    "vary observe",
    "been material",
    "divide sea",
    "work far",
    "ten let",
    "still late",
    "mile broke",
    "change the",
    "keep tall",
    "few try",
    "leave visit",
    "year story",
    "though soft",
    "appear put",
    "next develop",
    "flower machine",
    "wall since",
    "safe industry",
    "plan egg",
    "oh but",
    "bird clear",
    "heard each",
    "yes coast",
    "excite key",
    "village slow",
    "through between",
    "thousand surprise",
    "street a",
    "most don't",
    "move hunt",
    "possible cool",
    "weather six",
    "face dress",
    "build thought",
    "door is",
    "told in",
    "love school",
    "circle old",
    "look cow",
    "eat past",
    "once sky",
    "out cry",
    "equate brother",
    "weight exercise",
    "eye study",
    "heat letter",
    "think value",
    "hundred vowel",
    "experiment add",
    "off eight",
    "green such",
    "type self",
    "any whether",
    "above set",
    "top begin",
    "roll brought",
    "cat low",
    "which do",
    "house mountain",
    "after differ",
    "round believe",
    "other good",
    "strong complete",
    "need power",
    "surface our",
    "world call",
    "five act",
    "hour dark",
    "bright against",
    "to wood",
    "copy tell",
    "final knew",
    "than learn",
    "lot took",
    "ice fraction",
    "race produce",
    "water very",
    "syllable one",
    "with at",
    "sudden spell",
    "back travel",
    "warm game",
    "does verb",
    "buy read",
    "lead decide",
    "paragraph either",
    "hot wave",
    "these fine",
    "just arm",
    "usual earth",
    "system cloud",
    "port road",
    "side better",
    "why white",
    "well from",
    "talk up",
    "where bottom",
    "force here",
    "kill gave",
    "count front",
    "or full",
    "saw summer",
    "when as",
    "position bring",
    "gone life",
    "him night",
    "poor last",
    "field who",
    "north month",
    "class present",
    "winter press",
    "question room",
    "natural solve",
    "car list",
    "same miss",
    "length glass"
)